/**********************************************************************
*    This file was generated by Design Tool a product of: 
*       ARC International  
*       http://www.ARC.com/         
*                              
*       Fri Jun 08 11:29:32 2007
*   
*       Copyright (c) ARC International  
*       All rights reserved    
*   
*       This software embodies materials and concepts which are
*       confidential to ARC International and is made
*       available solely pursuant to the terms of a written license
*       agreement with ARC International.
*   
*   ********************************************************************/
/*   Global Functions and Data */
/* 
*  Resources  -   Number -  Memory Required
*  Kernel       -   N/A       -  N/A
*  Tasks        - 1       -  N/A
*  Msg Pools    -  0 of 16  -   N/A
*  Msg Queues   -  0 of 128   -  N/A
*  Mutexes       -  0    -  N/A
*  Semaphores   -  0 of 0     -   0x00
*  Events       -  0 of 0      -  0x00
*  Logs         -  1 of 16    -  N/A
*  	   Total:  N/A
*/ 
#include <mqx.h>
#include <bsp.h>
#include <log.h>
#include <klog.h>
#include <rtcs.h>
#include <enet.h>
#include "hello7.h"



/*   Function Code       */


/* End of File */
