#ifndef HOST_PROTOCOL_OPCODES_H
#define HOST_PROTOCOL_OPCODES_H

#include "defs610.h"
#include "PVG610_API.h"

///////////////////////////////////////////////////////////////////////////////
// ENUM
///////////////////////////////////////////////////////////////////////////////
/*
typedef enum
{
    // boot fw msg opcodes
    PVG610_COM_BOOT_HEADER_MSG_OPCODE_E,
    PVG610_COM_BOOT_DATA_MSG_OPCODE_E,
    PVG610_COM_BOOT_CHECKSUM_MSG_OPCODE_E,
    PVG610_COM_JUMP_TO_FW_MSG_OPCODE_E,

    // FW Invariants
    PVG610_COM_VERSION_GET_OPCODE_E,
    PVG610_COM_START_TRANSFERRING_BOOT_FW_OPCODE_E,
    PVG610_COM_BOOT_FW_DATA_MSG_OPCODE_E,
    PVG610_COM_BOOT_FW_JUMP_MSG_OPCODE_E,

    ///////////////////////////////////////////////////////////////////////////////
    // DO NOT PLACE/MOVE OPCODES ABOVE THIS BARRIER, UPGRADE MAY BE HARMED !!!!!!!!
    ///////////////////////////////////////////////////////////////////////////////

    // boot, flash, and upgrade

    // config file
    PVG610_COM_LOAD_COFIG_FILE_OPCODE_E,
    PVG610_COM_RUN_CONFIG_FILE_OPCODE_E,
    PVG610_COM_CONFIG_FILE_FROM_EMBEDDED_GET_OPCODE_E,

    // flash
    PVG610_COM_CFG_FILE_TO_FLASH_BURN_START_OPCODE_E,
    PVG610_COM_CFG_FILE_FROM_FLASH_LOAD_START_OPCODE_E,
    PVG610_COM_CFG_FILE_FROM_FLASH_ERASE_START_OPCODE_E,
    PVG610_COM_FLASH_HEADER_BURN_START_OPCODE_E,
    PVG610_COM_FLASH_FW_BURN_START_OPCODE_E,
    PVG610_COM_FLASH_FW_LOAD_START_OPCODE_E,
    PVG610_COM_FLASH_FW_ERASE_START_OPCODE_E,
    PVG610_COM_FLASH_INFO_GET_START_OPCODE_E,
    PVG610_COM_FLASH_FINISH_OPCODE_E,
    PVG610_COM_FLASH_DATA_OPCODE_E,
    PVG610_COM_FLASH_JUMP_OPCODE_E,

    // direct setup
    PVG610_COM_REGISTER_READ_OPCODE_E,
    PVG610_COM_REGISTER_WRITE_OPCODE_E,
    PVG610_COM_REGISTER_RANGE_READ_OPCODE_E,
    PVG610_COM_MULTIPLE_REGSITERS_READ_OPCODE_E,
    PVG610_COM_REGISTER_RANGE_WRITE_OPCODE_E,
    PVG610_COM_DWORD_FIFO_READ_OPCODE_E,
    PVG610_COM_DWORD_FIFO_WRITE_OPCODE_E,
    PVG610_COM_FROM_ROM_WRITE_OPCODE_E,

    // Status and Performance monitoring (general)
    PVG610_COM_ALARM_ENABLE_SET_OPCODE_E,
    PVG610_COM_ALARM_ENABLE_GET_OPCODE_E,
    PVG610_COM_ALARM_STATUS_GET_OPCODE_E,
    PVG610_COM_SYS_INFO_PARAMS_GET_OPCODE_E,
    PVG610_COM_HOST_INFO_SET_OPCODE_E,
    PVG610_COM_HOST_INFO_GET_OPCODE_E,

    // Status and Performance monitoring (modem)
    PVG610_COM_MODEM_STATUS_GET_OPCODE_E,
    PVG610_COM_MODEM_ACQUIRE_COUNTERS_GET_OPCODE_E,
    PVG610_COM_MODEM_FEC_COUNTERS_GET_OPCODE_E,
    PVG610_COM_MODEM_IQ_IMBALANCE_STATUS_GET_OPCODE_E,
    PVG610_COM_MODEM_EQUALIZER_STATUS_GET_OPCODE_E,
    PVG610_COM_MODEM_XPIC_STATUS_GET_OPCODE_E,
    PVG610_COM_MODEM_PREDISTORTION_COEFS_GET_OPCODE_E,
    PVG610_COM_MODEM_PREEMPHASIS_COEFS_GET_OPCODE_E,
    PVG610_COM_ACM_COUNTERS_GET_OPCODE_E,
    PVG610_COM_MODEM_IQ_SAMPLES_REC_OPCODE_E,
    PVG610_COM_MODEM_IQ_SAMPLES_GET_OPCODE_E,
    PVG610_COM_PROTECTION_STATUS_GET_OPCODE_E,

    // Status and Performance monitoring (networking)
    PVG610_COM_NET_FIFO_STATUS_GET_OPCODE_E,
    PVG610_COM_NET_ETH_STATUS_GET_OPCODE_E,
    PVG610_COM_NET_ETH_STATUS_GET_DONE_OPCODE_E,
    PVG610_COM_NET_ETH_PARAMS_SET_OPCODE_E,
    PVG610_COM_NET_E1_PM_GET_OPCODE_E,
    PVG610_COM_NET_STM1_PM_GET_OPCODE_E,
    PVG610_COM_NET_ETH_PM_GET_OPCODE_E,
    PVG610_COM_NET_E1_ALARM_GET_OPCODE_E,
    PVG610_COM_NET_STM1_ALARM_GET_OPCODE_E,

    //acm status
    PVG610_COM_ACM_CONFIGURATION_GET_OPCODE_E,

    //acmProfileGet
    PVG610_COM_ACM_PROFILE_MASK_GET_OPCODE_E,

    // Operative (general)
    PVG610_COM_HARD_RESET_OPCODE_E,
    PVG610_COM_GENERAL_CONTROL_SET_OPCODE_E,
    PVG610_COM_GENERAL_CONTROL_GET_OPCODE_E,
    PVG610_COM_MEMORY_GET_OPCODE_E,
    PVG610_COM_MEMORY_SET_OPCODE_E,
    PVG610_COM_LOOPBACK_SET_OPCODE_E,
    PVG610_COM_TRANSMITTER_MODE_SET_OPCODE_E,
    PVG610_COM_BLOCK_RESET_OPCODE_E,
    PVG610_COM_MODEM_IQ_IMBALANCE_TXTX_SET_OPCODE_E,

    // Operative (modem)
    PVG610_COM_ACQUIRE_START_OPCODE_E,
    PVG610_COM_MODEM_PREDISTORTION_COEFS_SET_OPCODE_E,
    PVG610_COM_MODEM_PREEMPHASIS_COEFS_SET_OPCODE_E,
    PVG610_COM_MODEM_RX_FREQ_OFFSET_SET_OPCODE_E,
    PVG610_COM_MODEM_TX_FREQ_OFFSET_SET_OPCODE_E,

    // Operative (acm)
    PVG610_COM_ACM_ENGINE_ENABLE_OPCODE_E,
    PVG610_COM_ACM_PROFILE_ENABLE_OPCODE_E,
    PVG610_COM_ACM_SWITCH_OPCODE_E,
    PVG610_COM_ACM_TDD_SWITCH_OPCODE_E,
    PVG610_COM_ACM_THRESHOLD_SET_E,
    PVG610_COM_ACM_IMPROVE_OPCODE_E,

    // Operative (networking)
    PVG610_COM_MAILBOX_MESSAGE_SEND_OPCODE_E,
    PVG610_COM_MAILBOX_MESSAGE_RECEIVE_OPCODE_E,
    PVG610_COM_PROTECTION_TX_MODE_SET_E,
    PVG610_COM_PROTECTION_RX_MODE_SET_E,
    PVG610_COM_PROTECTION_RX_FORCE_SET_E,
    PVG610_COM_NET_TRIBUTARY_HIZ_SET_E,
    PVG610_COM_NET_E1_CABLE_CONFIG_E,
    PVG610_COM_NET_E1_STM1_SIGNALS_FORCE_E,
    PVG610_COM_NET_E1_PRBS_MONITOR_CONNECT_E,
    PVG610_COM_NET_E1_PRBS_GENERATOR_CONNECT_E,
    PVG610_COM_NET_STM1_PRBS_MONITOR_CONNECT_E,
    PVG610_COM_NET_STM1_PRBS_GENERATOR_CONNECT_E,
    PVG610_COM_NET_PRBS_ERRORS_GET_E,
    PVG610_COM_NET_GPI_ERRORS_GET_E,
    PVG610_COM_NET_GPI_PRBS_GENERATOR_COMMAND_E,

    // peripherals
    PVG610_COM_I2C_TRANSACTION_START_OPCODE_E,
    PVG610_COM_I2C_IS_TRANSACTION_COMPLETE_OPCODE_E,
    PVG610_COM_SPI_TRANSACTION_START_OPCODE_E,
    PVG610_COM_SPI_IS_TRANSACTION_COMPLETE_OPCODE_E,

    // GPIO
    PVG610_GPIO_INT_CONFIG_OPCODE_E,
    PVG610_GPIO_WRITE_OPCODE_E,
    PVG610_GPIO_READ_OPCODE_E,

    // Others
    PVG610_COM_SYNC_TX_BYTE_CLK_OPCODE_E,
    PVG610_COM_XPIC_DELAY_SET_OPCODE_E,
    PVG610_COM_MODEM_XPIC_SLAVE_MUTE_SET_OPCODE_E,
    PVG610_COM_PREAMBLE_SET_OPCODE_E,
    PVG610_COM_IQ_DELAY_SET_OPCODE_E,
    PVG610_COM_DEBUG_PVG610_OPCODE_E,
    PVG610_COM_TX_RX_START_OPCODE_E,

    PVG610_COM_MAX_OPCODE_E,
} PVG610_COM_OPCODE_ENUM;
 */


    // boot fw msg opcodes
#define    PVG610_COM_BOOT_HEADER_MSG_OPCODE_E (0)
#define    PVG610_COM_BOOT_DATA_MSG_OPCODE_E (1)
#define    PVG610_COM_BOOT_CHECKSUM_MSG_OPCODE_E (2)
#define    PVG610_COM_JUMP_TO_FW_MSG_OPCODE_E (3)

    // FW Invariants
#define    PVG610_COM_VERSION_GET_OPCODE_E (4)
#define    PVG610_COM_START_TRANSFERRING_BOOT_FW_OPCODE_E (5)
#define    PVG610_COM_BOOT_FW_DATA_MSG_OPCODE_E (6)
#define    PVG610_COM_BOOT_FW_JUMP_MSG_OPCODE_E (7)

    ///////////////////////////////////////////////////////////////////////////////
    // DO NOT PLACE/MOVE OPCODES ABOVE THIS BARRIER, UPGRADE MAY BE HARMED !!!!!!!!
    ///////////////////////////////////////////////////////////////////////////////

    // boot, flash, and upgrade

    // config file
#define    PVG610_COM_LOAD_CONFIG_FILE_OPCODE_E (8)
#define    PVG610_COM_RUN_CONFIG_FILE_OPCODE_E (9)
#define    PVG610_COM_CONFIG_FILE_FROM_EMBEDDED_GET_OPCODE_E (10)

    // flash
#define    PVG610_COM_CFG_FILE_TO_FLASH_BURN_START_OPCODE_E (11)
#define    PVG610_COM_CFG_FILE_FROM_FLASH_LOAD_START_OPCODE_E (12)
#define    PVG610_COM_CFG_FILE_FROM_FLASH_ERASE_START_OPCODE_E (13)
#define    PVG610_COM_FLASH_HEADER_BURN_START_OPCODE_E (14)
#define    PVG610_COM_FLASH_FW_BURN_START_OPCODE_E (15)
#define    PVG610_COM_FLASH_FW_LOAD_START_OPCODE_E (16)
#define    PVG610_COM_FLASH_FW_ERASE_START_OPCODE_E (17)
#define    PVG610_COM_FLASH_INFO_GET_START_OPCODE_E (18)
#define    PVG610_COM_FLASH_FINISH_OPCODE_E (19)
#define    PVG610_COM_FLASH_DATA_OPCODE_E (20)
#define    PVG610_COM_FLASH_JUMP_OPCODE_E (21)

    // direct setup
#define    PVG610_COM_REGISTER_READ_OPCODE_E (22)
#define    PVG610_COM_REGISTER_WRITE_OPCODE_E (23)
#define    PVG610_COM_REGISTER_RANGE_READ_OPCODE_E (24)
#define    PVG610_COM_MULTIPLE_REGSITERS_READ_OPCODE_E (25)
#define    PVG610_COM_REGISTER_RANGE_WRITE_OPCODE_E (26)
#define    PVG610_COM_DWORD_FIFO_READ_OPCODE_E (27)
#define    PVG610_COM_DWORD_FIFO_WRITE_OPCODE_E (28)
#define    PVG610_COM_FROM_ROM_WRITE_OPCODE_E (29)

    // Status and Performance monitoring (general)
#define    PVG610_COM_ALARM_ENABLE_SET_OPCODE_E (30)
#define    PVG610_COM_ALARM_ENABLE_GET_OPCODE_E (31)
#define    PVG610_COM_ALARM_STATUS_GET_OPCODE_E (32)
#define    PVG610_COM_SYS_INFO_PARAMS_GET_OPCODE_E (33)
#define    PVG610_COM_HOST_INFO_SET_OPCODE_E (34)
#define    PVG610_COM_HOST_INFO_GET_OPCODE_E (35)

    // Status and Performance monitoring (modem)
#define    PVG610_COM_MODEM_STATUS_GET_OPCODE_E (36)
#define    PVG610_COM_MODEM_ACQUIRE_COUNTERS_GET_OPCODE_E (37)
#define    PVG610_COM_MODEM_FEC_COUNTERS_GET_OPCODE_E (38)
#define    PVG610_COM_MODEM_IQ_IMBALANCE_STATUS_GET_OPCODE_E (39)
#define PVG610_COM_MODEM_SLAVE_IQ_IMBALANCE_STATUS_GET_OPCODE_E	(40)
#define    PVG610_COM_MODEM_EQUALIZER_STATUS_GET_OPCODE_E (41)
#define    PVG610_COM_MODEM_XPIC_STATUS_GET_OPCODE_E (42)
#define    PVG610_COM_MODEM_PREDISTORTION_COEFS_GET_OPCODE_E (43)
#define    PVG610_COM_MODEM_PREEMPHASIS_COEFS_GET_OPCODE_E (44)
#define    PVG610_COM_ACM_COUNTERS_GET_OPCODE_E (45)
#define    PVG610_COM_MODEM_IQ_SAMPLES_REC_OPCODE_E (46)
#define    PVG610_COM_MODEM_IQ_SAMPLES_GET_OPCODE_E (47)
#define    PVG610_COM_PROTECTION_STATUS_GET_OPCODE_E (48)

    // Status and Performance monitoring (networking)
#define    PVG610_COM_NET_FIFO_STATUS_GET_OPCODE_E (49)
#define    PVG610_COM_NET_ETH_STATUS_GET_OPCODE_E (50)
#define    PVG610_COM_NET_ETH_STATUS_GET_DONE_OPCODE_E (51)
#define    PVG610_COM_NET_ETH_PARAMS_SET_OPCODE_E (52)
#define    PVG610_COM_NET_E1_PM_GET_OPCODE_E (53)
#define    PVG610_COM_NET_STM1_PM_GET_OPCODE_E (54)
#define    PVG610_COM_NET_ETH_PM_GET_OPCODE_E (55)
#define    PVG610_COM_NET_E1_ALARM_GET_OPCODE_E (56)
#define    PVG610_COM_NET_STM1_ALARM_GET_OPCODE_E (57)

    //acm status
#define    PVG610_COM_ACM_CONFIGURATION_GET_OPCODE_E (58)

    //acmProfileGet
#define    PVG610_COM_ACM_PROFILE_MASK_GET_OPCODE_E (59)

    // Operative (general)
#define    PVG610_COM_HARD_RESET_OPCODE_E (60)
#define    PVG610_COM_GENERAL_CONTROL_SET_OPCODE_E (61)
#define    PVG610_COM_GENERAL_CONTROL_GET_OPCODE_E (62)
#define    PVG610_COM_MEMORY_GET_OPCODE_E (63)
#define    PVG610_COM_MEMORY_SET_OPCODE_E (64)
#define    PVG610_COM_LOOPBACK_SET_OPCODE_E (65)
#define    PVG610_COM_TRANSMITTER_MODE_SET_OPCODE_E (66)
#define    PVG610_COM_BLOCK_RESET_OPCODE_E (67)
#define    PVG610_COM_MODEM_IQ_IMBALANCE_TXTX_SET_OPCODE_E (68)
#define PVG610_COM_UNSOLICITED_UART_MSGS_SET_OPCODE_E	(69)

    // Operative (modem)
#define    PVG610_COM_ACQUIRE_START_OPCODE_E (70)
#define    PVG610_COM_MODEM_PREDISTORTION_COEFS_SET_OPCODE_E (71)
#define    PVG610_COM_MODEM_PREEMPHASIS_COEFS_SET_OPCODE_E (72)
#define    PVG610_COM_MODEM_RX_FREQ_OFFSET_SET_OPCODE_E (73)
#define    PVG610_COM_MODEM_TX_FREQ_OFFSET_SET_OPCODE_E (74)

    // Operative (acm)
#define    PVG610_COM_ACM_ENGINE_ENABLE_OPCODE_E (75)
#define    PVG610_COM_ACM_PROFILE_ENABLE_OPCODE_E (76)
#define    PVG610_COM_ACM_SWITCH_OPCODE_E (77)
#define    PVG610_COM_ACM_TDD_SWITCH_OPCODE_E (78)
#define    PVG610_COM_ACM_THRESHOLD_SET_E (79)
#define    PVG610_COM_ACM_THRESHOLD_GET_E (80)
#define    PVG610_COM_ACM_IMPROVE_OPCODE_E (81)
#define    PVG610_COM_ACM_GPM_DYNAMIC_ALLOCATION_SET_OPCODE (82)
#define     PVG610_COM_FIFO_LEVEL_SET_OPCODE_E  (83)	   //>>>>>>>>>>>>>>>>>>>>>


    // Operative (networking)
#define    PVG610_COM_MAILBOX_MESSAGE_SEND_OPCODE_E (84)
#define    PVG610_COM_MAILBOX_MESSAGE_RECEIVE_OPCODE_E (85)
#define    PVG610_COM_PROTECTION_TX_MODE_SET_E (86)
#define    PVG610_COM_PROTECTION_RX_MODE_SET_E (87)
#define    PVG610_COM_PROTECTION_RX_FORCE_SET_E (88)
#define PVG610_COM_PROTECTION_SYS_MODE_SET_E (89)
#define    PVG610_COM_NET_TRIBUTARY_HIZ_SET_E (90)
#define    PVG610_COM_NET_E1_CABLE_CONFIG_E (91)
#define    PVG610_COM_NET_E1_STM1_SIGNALS_FORCE_E (92)
#define    PVG610_COM_NET_E1_PRBS_MONITOR_CONNECT_E (93)
#define    PVG610_COM_NET_E1_PRBS_GENERATOR_CONNECT_E (94)
#define    PVG610_COM_NET_STM1_PRBS_MONITOR_CONNECT_E (95)
#define    PVG610_COM_NET_STM1_PRBS_GENERATOR_CONNECT_E (96)
#define    PVG610_COM_NET_PRBS_ERRORS_GET_E (97)
#define    PVG610_COM_NET_GPI_ERRORS_GET_E (98)
#define    PVG610_COM_NET_GPI_PRBS_GENERATOR_COMMAND_E (99)

    // peripherals
#define    PVG610_COM_I2C_TRANSACTION_START_OPCODE_E (100)
#define    PVG610_COM_I2C_IS_TRANSACTION_COMPLETE_OPCODE_E (101)
#define    PVG610_COM_SPI_TRANSACTION_START_OPCODE_E (102)
#define    PVG610_COM_SPI_IS_TRANSACTION_COMPLETE_OPCODE_E (103)

    // GPIO
#define    PVG610_GPIO_INT_CONFIG_OPCODE_E (104)
#define    PVG610_GPIO_WRITE_OPCODE_E (105)
#define    PVG610_GPIO_READ_OPCODE_E (106)

    // Others
#define    PVG610_COM_SYNC_TX_BYTE_CLK_OPCODE_E (107)
#define    PVG610_COM_XPIC_DELAY_SET_OPCODE_E (108)
#define    PVG610_COM_MODEM_XPIC_SLAVE_MUTE_SET_OPCODE_E (109)
#define    PVG610_COM_PREAMBLE_SET_OPCODE_E (110)
#define    PVG610_COM_IQ_DELAY_SET_OPCODE_E (111)
#define    PVG610_COM_DEBUG_PVG610_OPCODE_E (112)
#define    PVG610_COM_TX_RX_START_OPCODE_E (113)

//#define    PVG610_COM_MAX_OPCODE_E (114)


#define      PVG610_COM_NET_ETH_PHY_REG_SET_OPCODE_E  (114)
#define      PVG610_COM_NET_ETH_PHY_REG_GET_OPCODE_E   (115)

    // ACM enhanced
#define      PVG610_COM_ACM_ENHANCED_ENGINE_MODE_SET_OPCODE_E  (116)
#define      PVG610_COM_ACM_ENHANCED_ENGINE_MODE_GET_OPCODE_E   (117)

    // network configuration
#define      PVG610_ETH_LARGE_FRAME_SET_OPCODE_E  (118)
#define      PVG610_ETH_IN_BAND_CONTROL_SET_OPCODE_E   (119)
#define      PVG610_ETH_PAUSE_SET_OPCODE_E	 (120)
#define      PVG610_ETH_VLAN_SET_OPCODE_E	  (121)
#define      PVG610_ETH_FIFO_LEVEL_SET_OPCODE_E	  (122)

    // tx tx calibration status
#define      PVG610_COM_TX_TX_CALIB_STATUS_GET_OPCODE_E	  (123)

    // tx mode
#define      PVG610_COM_TX_GAIN_ADJUST_MODE_SET_OPCODE_E   (124)
#define      PVG610_COM_TX_GAIN_ADJUST_MODE_GET_OPCODE_E    (125)

    // new Opcodes - Added at the end to ensure backwards compatibility 
#define      PVG610_COM_LIU_STATUS_GET_OPCODE		  (126)
#define      PVG610_COM_LOOPBACK_GET_OPCODE_E		   (127)
#define      PVG610_COM_TX_BAUDRATE_SET_OPCODE_E	    (128)
#define      PVG610_COM_RX_BAUDRATE_SET1_OPCODE_E	   (129)
#define      PVG610_COM_RX_BAUDRATE_SET2_OPCODE_E	    (130)

    // CAUTION! has to be the last Opcode at the list
#define      PVG610_COM_MAX_OPCODE_E					 (131)


#define  PVG610_COM_OPCODE_ENUM  BYTE			    

#endif

