/**********************************************************************
*    This file was generated by Design Tool a product of: 
*       ARC International  
*       http://www.ARC.com/         
*                              
*       Fri Jun 08 11:29:32 2007
*   
*       Copyright (c) ARC International  
*       All rights reserved    
*   
*       This software embodies materials and concepts which are
*       confidential to ARC International and is made
*       available solely pursuant to the terms of a written license
*       agreement with ARC International.
*   
*   ********************************************************************/
/*   Task Templates and 
**   MQX Initialization Structure, if required 
*/
/* 
*  Resources  -   Number -  Memory Required
*  Kernel       -   N/A       -  N/A
*  Tasks        - 1       -  N/A
*  Msg Pools    -  0 of 16  -   N/A
*  Msg Queues   -  0 of 128   -  N/A
*  Mutexes       -  0    -  N/A
*  Semaphores   -  0 of 0     -   0x00
*  Events       -  0 of 0      -  0x00
*  Logs         -  1 of 16    -  N/A
*  	   Total:  N/A
*/ 
#include <mqx.h>
#include <bsp.h>
#include <log.h>
#include <klog.h>
#include <rtcs.h>
#include <enet.h>
#include "hello7.h"

/* RTCS Protocol Table */
//uint_32 (_CODE_PTR_ RTCS_protocol_table[])(void) = 
//   {
//   RTCSPROT_IGMP,
//   RTCSPROT_UDP,
//   RTCSPROT_TCP,
//   NULL
//   };


/*   Task Templates  */ 
//tTASK_TEMPLATE_STRUCT  MQX_template_list[] = 
//t   {
 //t  { HELLO_INDEX, hello, 0xfa0L, 11L, "hello",
 //t      MQX_AUTO_START_TASK, 0, 0L },
//t   { 0, 0, 0, 0, 0, 0, 0, 0}
//t   };
//____________________________my   
//extern char LINK_DEFINED_START_KERNEL_MEMORY;
//extern char LINK_DEFINED_END_KERNEL_MEMORY;

//MQX_INITIALIZATION_STRUCT  MQX_init_struct =
//{
 //  /* PROCESSOR_NUMBER                */  BSP_DEFAULT_PROCESSOR_NUMBER,
 //  /* START_OF_KERNEL_MEMORY          */  BSP_DEFAULT_START_OF_KERNEL_MEMORY,
 //  /* END_OF_KERNEL_MEMORY            */  BSP_DEFAULT_END_OF_KERNEL_MEMORY,
 //  /* INTERRUPT_STACK_SIZE            */  BSP_DEFAULT_INTERRUPT_STACK_SIZE,
 //  /* TASK_TEMPLATE_LIST              */  MQX_template_list,
 //  /* MQX_HARDWARE_INTERRUPT_LEVEL_MAX*/  BSP_DEFAULT_MQX_HARDWARE_INTERRUPT_LEVEL_MAX,
 //  /* MAX_MSGPOOLS                    */  BSP_DEFAULT_MAX_MSGPOOLS,
 //  /* MAX_MSGQS                       */  BSP_DEFAULT_MAX_MSGQS,
 //  /* IO_CHANNEL                      */  BSP_DEFAULT_IO_CHANNEL,
 //  /* IO_OPEN_MODE                    */  BSP_DEFAULT_IO_OPEN_MODE
//};
//______________________________my


/* End of File */
